name: CI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      ref:
        required: false
        type: string

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  call-build-and-push:
    name: Call image build
    uses: federated-wiki/workflows/.github/workflows/build-and-push.yml@main
    if: ( inputs.ref == 0 )
    with:
      image-name: distribution
    secrets: inherit
  call-build-and-push-ref:
    name: Call tagged image build
    uses: federated-wiki/workflows/.github/workflows/build-and-push.yml@main
    if: ( inputs.ref != 0 )
    with:
      image-name: distribution
      ref: ${{ inputs.ref }}
    secrets: inherit
